name: Sync

on:
  push:
  schedule:
    - cron: '0 6,18 * * *'

jobs:
  sync_with_notion:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # Other steps that change files in the repository
      - name: Install npm and run
        run: |
          npm i
          npm run sync
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}

      - name: Get Current time
        id: current_time
        run: |
          echo "::set-output name=current_time::$(TZ='Asia/Tokyo' date +'%Y-%m-%dT%H:%M:%S')"

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[Actions] Sync with notion (${{ steps.current_time.outputs.current_time }})"
